import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header/header";
import Aside from "./components/aside/aside";
import Link from "next/link";

const geistSans = localFont({
   src: "./fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
});
const geistMono = localFont({
   src: "./fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
});

export const metadata = {
   title: "My First Project",
   description: "Generated by create next app", 
};

export default function RootLayout({ children }) {
   return (
      <html lang="pt-br"> 
         <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <Header />
            <Aside />
            {children}
         </body>
      </html>
   );
}
